version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: eklipse-llm-app
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: always
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: always
    networks:
      - backend

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always
    networks:
      - backend

volumes:
  prometheus_data:
  grafana_data:

networks:
  backend:
    driver: bridge
